import type { Driver } from '@/contracts/Roles';

export function getAllDrivers(): Driver[] {
  const drivers: Driver[] = [
    {
      id: 1,
      firstName: 'Oscar',
      lastName: 'Piastri',
      countryAbbreviation: 'AUS',
      price: 31400000,
      points: 108,
    },
    {
      id: 2,
      firstName: 'Lando',
      lastName: 'Norris',
      countryAbbreviation: 'GBR',
      price: 30300000,
      points: 138,
    },
    {
      id: 3,
      firstName: 'Charles',
      lastName: 'Leclerc',
      countryAbbreviation: 'MON',
      price: 18400000,
      points: 98,
    },
    {
      id: 4,
      firstName: 'Lewis',
      lastName: 'Hamilton',
      countryAbbreviation: 'GBR',
      price: 15300000,
      points: 9,
    },
    {
      id: 5,
      firstName: 'George',
      lastName: 'Russell',
      countryAbbreviation: 'GBR',
      price: 18500000,
      points: 108,
    },
    {
      id: 6,
      firstName: 'Kimi',
      lastName: 'Antonelli',
      countryAbbreviation: 'ITA',
      price: 6900000,
      points: 29,
    },
    {
      id: 7,
      firstName: 'Max',
      lastName: 'Verstappen',
      countryAbbreviation: 'NED',
      price: 18400000,
      points: 16,
    },
    {
      id: 8,
      firstName: 'Yuki',
      lastName: 'Tsunoda',
      countryAbbreviation: 'JPN',
      price: 4000000,
      points: 12,
    },
    {
      id: 9,
      firstName: 'Alexander',
      lastName: 'Albon',
      countryAbbreviation: 'THA',
      price: 6600000,
      points: 18,
    },
    {
      id: 10,
      firstName: 'Carlos',
      lastName: 'Sainz',
      countryAbbreviation: 'ESP',
      price: 3300000,
      points: 6,
    },
    {
      id: 11,
      firstName: 'Nico',
      lastName: 'Hulkenberg',
      countryAbbreviation: 'GER',
      price: 12700000,
      points: 24,
    },
    {
      id: 12,
      firstName: 'Gabriel',
      lastName: 'Bortoleto',
      countryAbbreviation: 'BRA',
      price: 3800000,
      points: 48,
    },
    {
      id: 13,
      firstName: 'Liam',
      lastName: 'Lawson',
      countryAbbreviation: 'NZL',
      price: 4700000,
      points: 24,
    },
    {
      id: 14,
      firstName: 'Isack',
      lastName: 'Hadjar',
      countryAbbreviation: 'FRA',
      price: 3500000,
      points: 10,
    },
    {
      id: 15,
      firstName: 'Lance',
      lastName: 'Stroll',
      countryAbbreviation: 'CAN',
      price: 6200000,
      points: 40,
    },
    {
      id: 16,
      firstName: 'Fernando',
      lastName: 'Alonso',
      countryAbbreviation: 'ESP',
      price: 6900000,
      points: 60,
    },
    {
      id: 17,
      firstName: 'Esteban',
      lastName: 'Ocon',
      countryAbbreviation: 'FRA',
      price: 4400000,
      points: 6,
    },
    {
      id: 18,
      firstName: 'Oliver',
      lastName: 'Bearman',
      countryAbbreviation: 'GBR',
      price: 4900000,
      points: 3,
    },
    {
      id: 19,
      firstName: 'Pierre',
      lastName: 'Gasly',
      countryAbbreviation: 'FRA',
      price: 5600000,
      points: 1,
    },
    {
      id: 20,
      firstName: 'Franco',
      lastName: 'Colapinto',
      countryAbbreviation: 'ARG',
      price: 3000000,
      points: 2,
    },
  ];

  return drivers;
}
